#+STARTUP: showall indent hidestars

* Chapter 1
  :PROPERTIES:
  :ORDERED:  t
  :END:

  Ниже приведена последовательность выражений. Какой результат
  напечатает интерпретатор в ответ на каждое из них?
  Предполагается, что выражения вводятся в том же порядке, в каком они написаны.

  ~Упражнение 1.1~

  #+BEGIN_SRC scheme
    (+ 5 3 4)
    ;; => 12

    (- 9 1)
    ;; => 8

    (/ 6 2)
    ;; => 3

    (+ (* 2 4) (- 4 6))
    ;; => 6

    (define a 3)
    ;; => 3

    (define b (+ a 1))
    ;; => 4

    (+ a b (* a b))
    ;; => 19

    (= a b)
    ;; => false

    (if (and (> b a) (< b (* a b)))
        b
        a)
    ;; => a (т.е. 4)

    (cond ((= a 4) 6)
          ((= b 4) (+ 6 7 a))
          (else 25))
    ;; => 16

    (+ 2
       (if (> b a)
           b
           a))
    ;; => 6

    (* (cond ((> a b) a)
             ((< a b) b)
             (else -1))
       (+ a 1))

    ;; => 16

  #+END_SRC

  ~Упражение 1.2~

  Переведите выражение в префиксную форму:

  5 + 4 + (2 − (3 − (6 + 4/5)))
  ____________________________
  3(6 − 2)(2 − 7)

  (4/5 в данном контексте означает дробь "четыре пятых")

  #+BEGIN_SRC scheme

    (/ (+ 4 5 (- 2 (- 3 (+ 6 (/ 4 5)))))
       (* 3 (- 6 2) (- 2 7)))

  #+END_SRC

  ~Упражнения 1.3~

  Определите процедуру, которая принимает в качестве аргументов три числа
  и возвращает сумму квадратов двух бо́льших из них.
  #+BEGIN_SRC scheme
    (define (sum-of-biggest-squares a b c)
      (cond ((or (and (> a b) (> b c))
                 (and (> a b) (= b c))
                 (and (> b a) (= b c))
                 (and (> b a) (= a c))) (+ (* a a) (* b b)))

            ((or (and (> c a) (> a b))
                 (and (> c a) (= a b))
                 (and (> c b) (> a b))
                 (and (> c b) (= a b))) (+ (* a a) (* c c)))

            ((or (and (> b a) (> c a))
                 (and (> b a) (= a c))
                 (and (> b c) (> c a))
                 (and (> b c) (= a b))) (+ (* b b) (* c c)))
            (else "Три числа равны")))


    (sum-of-biggest-squares 2 3 4)

    (sum-of-biggest-squares 5 1 2)

    (sum-of-biggest-squares 8 8 8)

    (sum-of-biggest-squares 9 3 1)

    (sum-of-biggest-squares 0 1 1)

    (sum-of-biggest-squares 1 1 0)

    (sum-of-biggest-squares 1 0 2)

    (sum-of-biggest-squares 2 0 2)
  #+END_SRC

  ~Упражнение 1.4~

  Заметим, что наша модель вычислений разрешает существование комбинаций, операторы кото-
  рых — составные выражения. С помощью этого наблюдения опишите, как работает следующая
  процедура:

  #+BEGIN_SRC scheme

    (define (a-plus-abs-b a b)
      ((if (> b 0)
           +
           -)
       a b))

    (a-plus-abs-b 3 5)

    (a-plus-abs-b 1 0)
  #+END_SRC

  Ответ: в зависимости от того, больше b нуля или нет, форма if вернет предикат
  "+" или "-", а возвращенный предикат будет применен к числам a и b.

  ~Упражнений 1.5~

  Бен Битобор придумал тест для проверки интерпретатора на то, с каким порядком
  вычислений он
  работает, аппликативным или нормальным. Бен определяет такие две процедуры:

  #+BEGIN_SRC scheme
  (define (p) (p))
  (define (test x y)
    (if (= x 0)
        0
        y))

  ;; Затем он вычисляет выражение

  (test 0 (p))
  #+END_SRC

  Какое поведение увидит Бен, если интерпретатор использует аппликативный порядок
  вычислений? Какое поведение он увидит, если интерпретатор использует нормальный
  порядок?
  Объясните Ваш ответ. (Предполагается, что правило вычисления особой формы if одинаково
  независимо от того, какой порядок вычислений используется.
  Сначала вычисляется выражение-предикат, и результат определяет,
  нужно ли вычислять выражение-следствие или альтернативу.)

  Ответ: мой интерпритатор использует нормальный порядок.

  При аппликативном порядке интерпритор сначала подстатавит все значения в параметры
  процедуры и только потом вычислит.

  Процедура P - это рекурсивный выозов самой себя без конца.
  аппликативный порядок даже не запустит процедуру.

  Нормальный же порядок сначала вычисляет то, что вычислить можно сразу, затем выполняет
  подстановку значений, если в этом есть необходимость и вычисляет новое выражение. И так
  до тех пор, пока выражение не будет вычислено полностью.

  Таким образом мы зациклимся навечно.

  ~Упражнение 1.6~

  Лиза П. Хакер не понимает, почему if должна быть особой формой. «Почему нельзя просто
  определить ее как обычную процедуру с помощью cond?» — спрашивает она. Лизина подруга
  Ева Лу Атор утверждает, что, разумеется, можно, и определяет новую версию if:
  #+BEGIN_SRC scheme

  (define (new-if predicate then-clause else-clause)
    (cond (predicate then-clause)
          (else else-clause)))

  #+END_SRC

  Обрадованная Лиза переписывает через new-if программу вычисления квадратного корня.
  Что получится, когда Лиза попытается использовать эту процедуру для вычисления
  квадратных корней? Объясните.
  #+BEGIN_SRC scheme

  (define (abs x)
    (cond ((> x 0) x)
          ((= x 0) 0)
          ((< x 0) (- x))))

  (define (square x) (* x x))

  (define (average x y)
    (/ (+ x y) 2))

  (define (improve guess x)
    (average guess (/ x guess)))

  (define (good-enough? guess x)
    ;; возводим предполагаемый корень числа в квадрат,
    ;; вычитаем его из заданного числа
    ;; молучаем модуль разости
    ;; проверям, меньше ли он 0.001
    (display "iteration\n")
    (display "guess is:")
    (display guess)
    (display "\n")
    (< (abs (- (square guess) x)) 0.001))

  ;; поиск корня с допустимой погрешностью
  (define (sqrt-iter guess x)
    ;; корень нашли?
    (new-if (good-enough? guess x)
        ;; да, вернуть корень
        guess
        ;; иначе считаем дальше
        (sqrt-iter (improve guess x)
                   x)))

  ;; считаем, что корень любого числа = 1
  (define (sqrt x)
    ;; вызываем основную процедуру
    (sqrt-iter 1.0 x))
  #+END_SRC

  Ответ: при запуске процедуры с new-if я получила ошибку о переполнении стека.
  Проблема в том, что срабатывают оба ветвления cond, это означает, возвращаемое
  значение предиката (вызов good-enogh? в нашем случае) не интерпритируется
  как "истина".


  ~Упражнение 1.7~
  Проверка good-enough?, которую мы использовали для вычисления квадратных корней, будет
  довольно неэффективна для поиска квадратных корней от очень маленьких чисел. Кроме
  того, в настоящих компьютерах арифметические операции почти всегда вычисляются
  с ограниченной точностью. Поэтому наш тест оказывается неадекватным и для очень больших
  чисел. Альтернативный подход к реализации good-enough? состоит в том, чтобы следить,
  как от одной итерации к другой изменяется guess, и остановиться, когда изменение
  оказывается небольшой долей значения приближения.
  Разработайте процедуру вычисления квадратного корня, которая использует такой
  вариант проверки на завершение. Верно ли, что на больших и маленьких числах она
  работает лучше?

  Ответ: неверно, поскольку процедура вынуждена вызывать саму себя одинаковое кол-во
  раз для good-enough? и my-good-enough?
  #+BEGIN_SRC scheme
  (define (my-good-enough? guess x)
    (display "iteration\n")
    (< (abs (- (square (improve guess x)) (square guess))) 0.001))

  ;; вызов с определенной в мане процедурой
  (define (sqrt-iter guess x)
    ;; корень нашли?
    (if (good-enough? guess x)
        ;; да, вернуть корень
        guess
        ;; иначе считаем дальше
        (sqrt-iter (improve guess x)
                   x)))

  ;; вызов с моей процедурой
  (define (sqrt-iter guess x)
    ;; корень нашли?
    (if (my-good-enough? guess x)
        ;; да, вернуть корень
        guess
        ;; иначе считаем дальше
        (sqrt-iter (improve guess x)
                   x)))
  #+END_SRC

  ~Упражнение 1.8~

  Метод Ньютона для кубических корней основан на том, что если Y является приближением к
  кубическому корню из X, то мы можем получить лучшее приближение по формуле:

  x/(y * y) + 2y
  ______________
  3

  С помощью этой формулы напишите процедуру вычисления кубического корня, подобную проце-
  дуре для квадратного корня.

  Чтоб узнать кубический корень из X, нужно разделить X на Y в квадрате, прибавить к
  получившемуся значению Y, умноженный на 2, и все это поделить на 3.

  Как найти Y?

  Предположим, что Y = 1.0

  #+BEGIN_SRC scheme
  (define (abs x)
    (cond ((> x 0) x)
          ((= x 0) 0)
          ((< x 0) (- x))))

  (define (square x) (* x x))

  (define (cube x) (* x x x))

  ;; (define (my-average x y)
  ;;   (/ (+ x y) 3))

  (define (formula-realization guess x)
    ( / (+ (/ x (square guess )) (* 2 guess ))
        3))

  ;; (define (improve guess x)
  ;;   (average guess (/ x guess)))

  (define (good-enough? guess x)
    ;; возводим предполагаемый корень числа в квадрат,
    ;; вычитаем его из заданного числа
    ;; молучаем модуль разости
    ;; проверям, меньше ли он 0.001
    (display "iteration\n")
    (display "guess is:")
    (display guess)
    (display "\n")
    (< (abs (- (cube (formula-realization guess x)) x))
       0.001))

  (define (my-good-enough? guess x)
    (display "iteration\n")
    (display "guess is:")
    (display guess)
    (display "\n")
    (< (abs (- (cube (formula-realization guess x)) (cube guess))) 0.001))

  ;; поиск корня с допустимой погрешностью
  (define (sqrt-iter guess x)
    ;; корень нашли?
    (if (my-good-enough? guess x)
        ;; да, вернуть корень
        guess
        ;; иначе считаем дальше
        (sqrt-iter (formula-realization guess x) x)))

  ;; считаем, что корень любого числа = 1
  (define (sqrt x)
    ;; вызываем основную процедуру
    (sqrt-iter 1.0 x))

  #+END_SRC

  ~Упражнение 1.9~

  Каждая из следующих двух процедур определяет способ сложения двух положительных целых
  чисел с помощью процедур inc, которая добавляет к своему аргументу 1, и dec, которая
  отнимает от своего аргумента 1.

  Используя подстановочную модель, проиллюстрируйте процесс, порождаемый каждой из этих
  процедур, вычислив (+ 4 5). Являются ли эти процессы итеративными или рекурсивными?

  #+BEGIN_SRC scheme
  (define (+ a b)
    (if (= a 0)
        b
        (inc (+ (dec a) b))))

  (define (+ a b)
    (if (= a 0)
        b
        (+ (dec a) (inc b))))
  #+END_SRC

  Ответ: первая процедура - это линейный рекурсивный процесс. Вторая - итеративный
  линейный процесс, он же хвостовая рекурсия.

  ~Упражнение 1.10~

  Следующая процедура вычисляет математическую функцию, называемую функцией Аккермана.

  Каковы значения следующих выражений?
  (A 1 10) => 1024
  (A 2 4)  => 65536
  (A 3 3)  => 65536
  #+BEGIN_SRC scheme
  (define (A x y)
    (display "----\n")
    (display "x:")
    (display x)
    (display "\n")
    (display "y:")
    (display y)
    (display "\n")
    (cond ((= y 0) 0)
          ((= x 0) (* 2 y))
          ((= y 1) 2)
          (else (A (- x 1)
                   (A x (- y 1))))))
  #+END_SRC


  Рассмотрим следующие процедуры, где A — процедура, определенная выше:
  (define (f n) (A 0 n))
  (define (g n) (A 1 n))
  (define (h n) (A 2 n))
  (define (k n) (* 5 n n))

  Дайте краткие математические определения функций, вычисляемых процедурами f, g и h для
  положительных целых значений n.

  f(n) = A(0 n)
  g(n) = A(1 n)
  h(n) = A(2 n)

  ~Шпаргалка по fib~
  #+BEGIN_SRC scheme
  (define (fib n sp)
    (space sp)
    (display "n:")
    (display n)
    (display "\n")
    (cond ((= n 0) (let ((answer 0))
                     (space sp)
                     (display "first\n")
                     0))
          ((= n 1) (let ((answer 1))
                     (space sp)
                     (display "second\n")
                     1))
          (else (let ((answer 10))
                  (space sp)
                  (display "else\n")
                  (+ (fib (- n 1) (+ 1 sp))
                     (fib (- n 2) (+ 1 sp)))))))

  (define (fib n sp)
    (fib-iter 1 0 n sp))

  (define (fib-iter a b count sp)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1) (+ sp 1))))

  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))
  #+END_SRC

  ~Упражнение 1.11~

  Функция f определяется правилом:
  f (n) = n, если n < 3, и f (n) = f (n − 1) + f (n − 2) + f (n − 3), если n ≥ 3.
  Напишите процедуру, вычисляющую f с помощью рекурсивного процесса.
  Напишите процедуру, вычисляющую f с помощью итеративного процесса.

  #+BEGIN_SRC scheme
  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))

  (define (f n sp)
    (space sp)
    (display "n:")
    (display n)
    (display "\n")
    (if (< n 3)
        n
        (+ (f (- n 1) (+ sp 1)) (f (- n 2) (+ sp 1)) (f (- n 3) (+ sp 1)))))

  (define (iter-f a b c count sp)
    (space sp)
    (display "A:")
    (display a )
    (display "\n")
    (space sp)
    (display "B:")
    (display b )
    (display "\n")
    (space sp)
    (display "C:")
    (display c )
    (display "\n")
    (space sp)
    (display "count:")
    (display count )
    (display "\n")
    (if (= count 0)
        c
        (iter-f (+ a b c) a b (- count 1) (+ sp 1))))

  (define (f n sp)
    (iter-f 2 1 0 n sp))
  #+END_SRC

  ~Упражнение 1.12~

  Дан треугольник Паскаля (см. стр. 57)

  Все числа по краям треугольника равны 1, а каждое число внутри треугольника равно сумме
  двух чисел над ним. Напишите процедуру, вычисляющую элементы треугольника Паскаля с
  помощью рекурсивного процесса.

  PS скорее всего имеется в виду вычисление суммы коэфициентов. Т.е. надо опираться на
  следующее:
  сумма биномиальных коэффициентов равна числу 2, возведенному в степень, равную
  показателю степени бинома Ньютона. Т.е. сумма коэфициэнтов третьей строчки треугольника
  Паскаля будет равна 8, поскольку 2 в третьей степени = 8.

  #+BEGIN_SRC scheme
   ;; n = строка треугольника Паскаля. Нумерция строк наинчается от нуля.
   ;; k = кол-во элементов в строке. Всегда равно номеру строки + 1
   (define (paskal n)
     (p n (+ n 1)))

   (define (p n k)
     (if (or (= n 0) (= n k))
         1
         (+ (p (- n 1) (- k 1))
            (p (- n 1) k))))
  #+END_SRC

  ~Упражнение 1.13~
  Докажите, что Fib(n) есть целое число, ближайшее к φ в степени n / √5,
  где φ = (1 + √5)/2. Указание: пусть ψ = (1 − √5)/2.
  С помощью  определения чисел Фибоначчи (см. раздел 1.2.2) и индукции докажите,
  что Fib(n) = (φ в степени n − ψ в степени n )/ √5.

  Определение числел Фибоначчи: каждое последующее число = сумме предыдущих двух:
  F(n) = 0, если n = 0
  F(n) = 1, если n = 1
  F(n) = F(n - 1) + F (n - 2) во всех остальных случаях

  φ = (1 + √5)/2 - это формула золотого сечения

  Полагаю, что под индукцией понимается математическая индукция, т.е. если базис индукции
  верен (будем считать его 1 или же P1), то верно и Pn, а значит справедливо будет
  сказать, что верно Pn + 1. Иллюстрация этого утверждения - принцип домино: если упала
  первая косточка домино, то упадут и все последующие.

  Значит, нам нужно доказать, что
  Fib(1) есть целое число, ближайшее к φ в степени 1 /√5, где φ = (1 + √5)/2  -  это
  будет базис нашей индукции.

  Воспользуемся определенными в ~упражнениеи 1.7~ функциями, чтоб извлекать квадратные
  корни.
  #+BEGIN_SRC scheme
   (define (abs x)
     (cond ((> x 0) x)
           ((= x 0) 0)
           ((< x 0) (- x))))

   (define (square x) (* x x))

   (define (average x y)
     (/ (+ x y) 2))

   (define (improve guess x)
     (average guess (/ x guess)))

   (define (good-enough? guess x)
     ;; возводим предполагаемый корень числа в квадрат,
     ;; вычитаем его из заданного числа
     ;; молучаем модуль разости
     ;; проверям, меньше ли он 0.001
     (< (abs (- (square guess) x)) 0.001))

   ;; поиск корня с допустимой погрешностью
   (define (sqrt-iter guess x)
     ;; корень нашли?
     (if (good-enough? guess x)
         ;; да, вернуть корень
         guess
         ;; иначе считаем дальше
         (sqrt-iter (improve guess x)
                    x)))

   ;; считаем, что корень любого числа = 1
   (define (sqrt x)
     ;; вызываем основную процедуру
     (sqrt-iter 1.0 x))
  #+END_SRC

  #+BEGIN_SRC scheme
  (define (fib n)
    (fib-iter 1 0 n))

  (define (fib-iter a b count)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1))))

  ;; вычисление фи
  (define (fi)
    ( / (+ 1 (sqrt 5)) 2))

  ;; вычисление пси
  (define (psi)
    ( / (- 1 (sqrt 5)) 2))

  ;; возведение числа в степень (написано криво, я знаю)
  (define (extent x pr-x n)
    (cond ((= n 0) 1)
          ((= n 1) x)
          (else (extent (* x pr-x) pr-x (- n 1)))))

  ;; если базис индукции верен, вычисляем условие с n
  ;; внимаение, наблюдается погрешность приблиительно на 0.001, которая становится выше
  ;; на больших числах
  ;; P.S. формально вычисление условия с n не требуется, т.к. если базис индукции
  ;; верен, то и условие с n верно
  (define (proof n)
    (if (= (fib 1) ( / (- (extent (fi) (fi) 1) (extent (psi) (psi) 1)) (sqrt 5)))
        (if (or (> (- (fib n) ( / (- (extent (fi) (fi) n) (extent (psi) (psi) n)) (sqrt 5)))
                   0.1)
                (< (- (fib n) ( / (- (extent (fi) (fi) n) (extent (psi) (psi) n)) (sqrt 5)))
                   0.1)
                (= (fib n) ( / (- (extent (fi) (fi) n) (extent (psi) (psi) n)) (sqrt 5))))

            #t
            (let ((f #f))
              (display (fib n))
              (display "\n")
              (display ( / (- (extent (fi) (fi) n) (extent (psi) (psi) n)) (sqrt 5)))
              (display "\n")
              f))))

  #+END_SRC


  ~Шпаргалка по размену монет~

  #+BEGIN_SRC scheme

  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))

  (define (cc amount kinds-of-coins sp)
    (space sp)
    (display "amount:")
    (display amount)
    (display "\n")
    (space sp)
    (display "kinds-of-coins:")
    (display kinds-of-coins)
    (display "\n")
    (cond ((= amount 0) 1)
          ((or (< amount 0) (= kinds-of-coins 0)) 0)
          (else (+ (cc amount
                       (- kinds-of-coins 1) (+ sp 1))
                   (cc (- amount
                          (first-denomination kinds-of-coins))
                       kinds-of-coins (+ sp 1))))))

  (define (first-denomination kinds-of-coins)
    (cond ((= kinds-of-coins 1) 1)
          ((= kinds-of-coins 2) 5)
          ((= kinds-of-coins 3) 10)
          ((= kinds-of-coins 4) 25)
          ((= kinds-of-coins 5) 50)))

  (define (count-change amount)
    (cc amount 5 0))
  #+END_SRC

  ~Упражнение 1.15~

  Синус угла (заданного в радианах) можно вычислить, если воспользоваться приближением
  sin x ≈ x при малых x и употребить тригонометрическое тождество (см. стр 59)
  для уменьшения значения аргумента sin. (В этом упражнении мы будем считать, что угол
  «достаточно мал», если он не больше 0.1 радиана.) Эта идея используется в следующих
  процедурах:

  #+BEGIN_SRC scheme
  (define (cube x) (* x x x))

  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))

  (define (p x count sp)
    (space sp)
    (display "count:")
    (display count)
    (display "\n")
    (- (* 3 x) (* 4 (cube x))))

  (define (sine angle count)
    (if (not (> (abs angle) 0.1))
        angle
        (p (sine (/ angle 3.0) (+ 1 count)) (+ count 1) (+ sp 1))))
  #+END_SRC

  а. Сколько раз вызывается процедура p при вычислении (sine 12.15)?
  б. Каковы порядки роста в терминах количества шагов и используемой памяти
  (как функция a) для процесса,
  порождаемого процедурой sine при вычислении (sine a)?

  Ответ: p выполнится 5 раз.

  ?

  ~Упражнение 1.16~

  Напишите процедуру, которая развивается в виде итеративного процесса и реализует
  возведение в степень за логарифмическое число шагов, как fast-expt.
  (Указание: используя наблюдение, что (b^n/2 )^2 = (b^2 )^n/2 ,
  храните, помимо значения степени n и основания b, дополнительную переменную состояния
  a, и определите переход между состояниями так, чтобы произведение ab^n от
  шага к шагу не менялось. Вначале значение a берется равным 1, а ответ получается
  как значение a в момент окончания процесса.
  В общем случае метод определения инварианта (invariant quantity), который не изменяется
  при переходе между шагами, является мощным способом размышления о построении
  итеративных алгоритмов.)

  Первоначальный вариант fast-expt:
  o
  #+BEGIN_SRC scheme
  (define (even? n)
    (= (remainder n 2) 0))

  (define (fast-expt b n)
    (cond ((= n 0) 1)
          ((even? n) (square (fast-expt b (/ n 2))))
          (else (* b (fast-expt b (- n 1))))))
  #+END_SRC

  Первод задания на русский язык:
  - функция должна реализовывать хвостовую рекурсию вместо линейной
  - функция должна работать по тому же принципу, что и fast-expt: т.е. использовть
логарифмическое кол-во шагов, а не линейное
- функция должна использовать 3 переменные: n - значение степени,
 b - основание, а - переменная состояния
- переменная состояния - это, видимо, аккумулятор. Т.е. в нем будет накапливаться
значение, которое вернет функция. Изначально его значение = 1.
- дана подсказка: можно сначала разделить степень на два, возвести число в степень и
затем возвести результат в квадрат или сначала возвести число в квадрат, а затем
в разделенную на два степень.
- переход между состояниями, т.е. между итерациями/вызовами функции должен быть
  определен так, чтоб произведение от а*b^n не менялось (что имеется в виду?)
Возможный вариант:
- n делится на 2 на каждой итерации
- a = a * b на каждой итерации (здесь была ошибка: не на каждой итерации, а только
на последней. Т.е. акум все равно b, и только на последней итерации, когда
n = 1, мы перемножаем a и b, т.е. умножаем b на единицу, поскольку любой число
в степени 1 = то же самое число)

#+BEGIN_SRC scheme
  (define (even? n)
    (= (remainder n 2) 0))

  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))

  (define (fast-expt b n)
    (my-fast-expt b n 1 0))

  (define (my-fast-expt b n a sp)
    (space sp)
    (display "a:")
    (display a)
    (display "\n")
    (space sp)
    (display "n:")
    (display n)
    (display "\n")
    (space sp)
    (display "b:")
    (display b)
    (display "\n")
    (cond ((= n 0) a)
          ((even? n) (my-fast-expt (* b b) (/ n 2) a (+ 1 sp)))
          (else (my-fast-expt b (- n 1) (* a b) (+ 1 sp)))))

#+END_SRC
~Упражнение 1.17~

Алгоритмы возведения в степень из этого раздела основаны на повторяющемся
умножении. Подобным же образом можно производить умножение с помощью повторяющегося
сложения.
Следующая процедура умножения (в которой предполагается,
что наш язык способен только складывать, но не умножать) аналогична процедуре expt:

#+BEGIN_SRC scheme

  (define (* a b)
    (if (= b 0)
        0
        (+ a (* a (- b 1)))))

#+END_SRC

Этот алгоритм затрачивает количество шагов, линейно пропорциональное b.
Предположим теперь, что, наряду со сложением, у нас есть операции double,
которая удваивает целое число, и halve, которая делит (четное) число на 2.
Используя их, напишите процедуру, аналогичную fast-expt,
которая затрачивает логарифмическое число шагов.

Итак, нам фактически нужно реализовать процедуру умножения, не используя само
умножение и затратить на это логарифмическое кол-во шагов.
Если "b" четное, то мы делим b на 2, затем складываем "a" с самим собой до тех пор,
пока b не станет 0 (1?).

#+BEGIN_SRC scheme

  (define (double a)
    (+ a a))

  (define (halve a)
    (/ a 2))

  (define (even? n)
    (= (remainder n 2) 0))

  (define (multiple a b)
    (cond ((or (= b 0) (= a 0)) 0)
          ((= b 1) a)
          ((= a 1) b)
          ((even? b) (multiple (double a) (halve b)))
          (else (+ a (multiple a (- b 1))))))

#+END_SRC

~Упражнение 1.18~

Используя результаты упражнений 1.16 и 1.17, разработайте процедуру, которая порождает
итеративный процесс для умножения двух чисел с помощью сложения, удвоения и деления пополам,
и затрачивает логарифмическое число шагов.

Дана подсказка: данный алгоритм называется "метод русского крестьянина" или
"египетский" метод.

#+BEGIN_SRC scheme
  (define (double a)
    (+ a a))

  (define (halve a)
    (/ a 2))

  (define (even? n)
    (= (remainder n 2) 0))

  (define (new-multiple a b accum)
    (cond ((or (= b 0) (= a 0)) accum)
          ((= b 1) (+ a accum))
          ((= a 1) b)
          ((even? b) (new-multiple (double a) (halve b) accum))
          (else (new-multiple a (- b 1) (+ a accum)))))

  (define (multiple a b)
    (new-multiple a b 0))
#+END_SRC

~Упражнение 1.19~

уществует хитрый алгоритм получения чисел Фибоначчи за логарифмическое число шагов.
Вспомните трансформацию переменных состояния a и b процесса fib-iter из раздела 1.2.2

a ← a + b и b ← a. Назовем эту трансформацию T и заметим, что n-кратное применение T ,
начиная с 1 и 0, дает нам пару Fib(n + 1) и Fib(n). Другими словами, числа Фибоначчи
получаются путем применения T^n , n-ой степени трансформации T , к паре (1,0).
Теперь рассмотрим T как частный случай p = 0, q = 1 в семействе трансформаций T pq ,
где Tpq преобразует пару (a, b) по правилу a ← bq + aq + ap, b ← bp + aq.
Покажите, что двукратное применение трансформации Tpq равносильно однократному
применению трансформации Tp ′q ′ того же типа, и вычислите p ′ и q ′ через p и q.
Это дает нам прямой способ возводить такие трансформации в квадрат, и
таким образом, мы можем вычислить T n с помощью последовательного возведения в квадрат, как в
процедуре fast-expt. Используя все эти идеи, завершите следующую процедуру, которая
дает результат за логарифмическое число шагов.

Перевод на русский язык:
есть некая трансформация, которая называется Т. Она работает так:  a ← a + b и b ← a
Му говорим что применение этой трансформации какое-то кол-во раз к числам 1 0 дает
нам в конечном итоге формулу Фибоначи, а вернее, пару Fib(n + 1) и Fib(n). Иными
словами можно сказать, что числа Фибоначчи получаются, если применить трансформацию Т
заданное кол-во раз, т.е. Т^n к паре 1 и 0.

Теперь скажем, что это частный случай в целом семестве трансформаций Tpq, где
p = 0, q = 1.
Семейство этих трансформаций работает по правилу: a ← bq + aq + ap, b ← bp + aq,
преобразовывая таким образом а и b.

Задание: у нас есть семейство трансформаций Tpq и какая-то конкретная трансформация
этого семейства Tp ′q ′, т.е. за p ′q` скрыты реальные числа.
Нам нужно вычислить их через p и q, зная, что однократное применение Tp ′q ′
будет равносильно двукратному применению Tpq, т.е. p ′и q ′ - в 2 раза больше, чем p и
q.

#+BEGIN_SRC scheme
  (define (fib n)
    (fib-iter 1 0 0 1 n 0))

  (define (space n)
    (if (< n 1)
        0
        (let ((sos 1))
          (display " ")
          (space (- n 1)))))

  (define (fib-iter a b p q count sp)
    (space sp)
    (display "a:")
    (display a)
    (display "\n")
    (space sp)
    (display "b:")
    (display b)
    (display "\n")
    (space sp)
    (display "p:")
    (display p)
    (display "\n")
    (display "q:")
    (display q)
    (display "\n")
    (space sp)
    (display "count:")
    (display count)
    (display "\n")
    (cond ((= count 0) b)
          ((even? count)
           (fib-iter a
                     b
                     (+ (* p p) (* q q))
                     (+ (* 2 p q) (* q q))
                     (/ count 2) (+ sp 1)))
          (else (fib-iter (+ (* b q) (* a q) (* a p))
                          (+ (* b p) (* a q))
                          p
                          q
                          (- count 1) (+ sp 1)))))
#+END_SRC

~Упражнение 1.20~

Процесс, порождаемый процедурой, разумеется, зависит от того, по каким правилам
работает интерпретатор. В качестве примера рассмотрим итеративную процедуру gcd,
приведенную выше. Предположим, что мы вычисляем эту процедуру с помощью нормального
порядка, описанного в разделе 1.1.5.
(Правило нормального порядка вычислений для if описано в упражнении 1.5.)
Используя подстановочную модель для нормального порядка, проиллюстрируйте процесс,
порождаемый при вычислении (gcd 206 40) и укажите, какие операции вычисления остатка
действительно выполняются. Сколько операций remainder выполняется на самом деле при вычислении
(gcd 206 40) в нормальном порядке? При вычислении в аппликативном порядке?

#+BEGIN_SRC scheme

(define (gcd a b)
    (if (= b 0)
        a
        (gcd b (remainder a b))))

#+END_SRC

Итак, нормальный порядок вычислений будет сначала подставит все аргументы и только
потом запустит процедуру "«полная подстановка, затем редукция".If будет работать
одинаково и при аппликативном, и при нормальном порядке.

Апликативный порядок будет осуществляться:

Даны аргументы 206 и 40. Их можно сразу подставить и запустить процедуру gcd.
Сработает ветка if-a false, т.к. 40 != 0. Процедура remainder получит аргументы
206 и 40,вернет остаток от деления, запустится рекурсивный вызов gcd и так будет до тех пор, пока
b не окажется = 0. Иными словами, мы будем сначала вычислять аргументы, а затем
запускать процедуру.

При нормальном порядке аргументы remainder не будут вычислены.
Проще показать это через код:
#+BEGIN_SRC scheme
;; доделать!
  ;; первый вызов
  (gcd 206 40 ) ->

  (if (= 40 0)
      206
      (gcd 40 (remainder 206 40))) ->

  ;; рекурсивый вызов 1
  (gcd 40 (remainder 206 40)) ->

  (if (= (remainder 206 40) 0)
      40
      (gcd (remainder 206 40) (remainder 40
                                         (remainder 206 40)))) ->
  ;; рекурсивный вызов 2
  (gcd (remainder 206 40) (remainder 40
                                     (remainder 206 40))) ->

  (if (= (remainder 40
                    (remainder 206 40)) 0)

      (remainder 206 40)
      (gcd (remainder 40
                      (remainder 206 40))
           (remainder (remainder 206 40)
                      (remainder 40
                                 (remainder 206 40))))) ->




#+END_SRC



~Шпаргалка по тесту Ферма~

#+BEGIN_SRC scheme
  (define (square x) (* x x))

  ;; принимает основание, степень и модуль
  (define (expmod base exp m)
    ;; если степень = 0, вернуть 1
    (cond ((= exp 0) 1)
          ;; если степень четная,
          ((even? exp)
           ;; рекурсивно вызываем с процедуру с степенью поделенной на 2,
           ;; когда достигнем дна рекурсии, отктимся назад, получим число, возведенное
           ;; в степень, деленную на 2 и возведем его в квадрат (см алгоритм fast-expt)
           ;; затем передадим результат и модуль в процедуру reminder,
           ;; которая вернет нам остаток от деления данного числа на модуль
           (remainder (square (expmod base (/ exp 2) m))
                      m))
          ;; если степень не четная, отнимаем от степени 1, рекурсивно вызываем процедуру,
          ;; достигаем дна рекурсии, откатываем назад, умножаем полученный результат
          ;; основание и передаем все в remainder, чтоб, опять же, получить остаток
          (else
           (remainder (* base (expmod base (- exp 1) m))
                      m))))

  ;; вызов exmod  с рандомным числом от "a" до n-1
  (define (fermat-test n)
    (define (try-it a)
      (= (expmod a n n) a))
    (try-it (+ 1 (random (- n 1)))))

  ;; если тест Ферма прошел заданное кол-во раз, мы считаем, что число n простое
  (define (fast-prime? n times)
    (cond ((= times 0) #t)
          ((fermat-test n) (fast-prime? n (- times 1)))
          (else #f)))
#+END_SRC


~Упражнение 1.21~

С помощью процедуры smallest-divisor найдите наименьший делитель следующих чисел:
199, 1999, 19999.

#+BEGIN_SRC scheme
  (define (square x) (* x x))

  (define (divides? a b)
    (= (remainder b a) 0))

  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (+ test-divisor 1)))))

  (define (smallest-divisor n)
    (find-divisor n 2))

  (define (prime? n)
    (= n (smallest-divisor n)))
#+END_SRC

Для числа 199 - наименьший делитель само число, т.к. это простое число, для 1999 - само
число по аналогичной причине (вообще-то наименьший делитель для них должен быть 1)

Для числа 19999 ответ 7, т.к. это непростое число.


~Упражнение 1.22~
Бо́льшая часть реализаций Лиспа содержат элементарную процедуру runtime, которая
возвращает целое число, показывающее, как долго работала система (например, в
миллисекундах).

Следующая процедура timed-prime-test, будучи вызвана с целым числом n, печатает n и
проверяет, простое ли оно. Если n простое, процедура печатает три звездочки и количество
времени, затраченное на проверку.

Используя эту процедуру, напишите процедуру search-for-primes, которая проверяет на
простоту все нечетные числа в заданном диапазоне. С помощью этой процедуры найдите
наименьшие три простых числа после 1000; после 10 000; после 100 000; после 1 000 000.
Посмотрите, сколько времени затрачивается на каждое простое число.
Поскольку алгоритм проверки имеет порядок роста Θ(√n), Вам следовало бы ожидать,
что проверка на простоту чисел, близких к 10 000, занимает в 10 раз больше времени, чем
для чисел, близких к 1000. Подтверждают ли это Ваши замеры времени?
Хорошо ли поддерживают предсказание √n данные для 100 000 и 1 000 000?
Совместим ли Ваш результат с предположением, что программы на Вашей машине затрачивают
на выполнение задач время, пропорциональное числу шагов?


#+BEGIN_SRC scheme
  (define (report-prime start-time end-time)
    (display " *** ")
    (display (- (cdr end-time) (cdr start-time)))
    (display "\n")
    #t)

  (define (start-prime-test n start-time)
    (if (prime? n)
        (report-prime start-time (gettimeofday))
        #f))

  (define (timed-prime-test n)
    (newline)
    (display n)
    (start-prime-test n (gettimeofday)))

#+END_SRC

Отсутствует процедура runtime, пришлось заменить на такой "кустарный" таймер.
gettimeofday пару значений: секунды и микросекунды с 1.1.1970.

Добавила возвращаемые значение #t, если число простое, и #f - если нет, так легче
написать search-for-primes.

Процедура принимает диапазон, в котором должна найти простые числа, и кол-во этих
простых чисел.
#+BEGIN_SRC scheme
  (define (search-for-primes start-num end-num count)
    (cond ((= (remainder start-num 2) 0) (search-for-primes (+ 1 start-num) end-num count))
          ((or (= count 0) (= start-num end-num)) (display "finished\n"))
          ((timed-prime-test start-num)
           (search-for-primes (+ 2 start-num) end-num (- count 1)))
          (else (search-for-primes (+ 2 start-num) end-num count))))

#+END_SRC

Форматный вывод:
1009 *** 11
1013 *** 14
1019 *** 10

10007 *** 65
10009 *** 72
10037 *** 67

100003 *** 168
100019 *** 167
100043 *** 119

1000003 *** 546
1000033 *** 546
1000037 *** 679

Итак, если верить полученному выводу, то на поиск простых чисел, ближайших к
10 000, уходит не в 10 раз больше времени, чем для поиска простых чисел, ближайших к
1000. Возможно, дело во внутренней оптимизации.

Если я правильно понимаю обозначение Θ(√n), то число шагов будет расти как "квабратный
корень от n", т.е. кол-во шагов при n = 1000 приблизительно равно 32, при n = 10 000
кол-во шагов приблизительно равно 100, при n = 100 000 число шагов приблизительно 320,
при n = 1 000 000 приблизительно 1000. Т.е. чтоб найти три простых числа рядом
с 100 00 нужно в 10 раз меньше шагов чем для 1 000 000, и в 10 раз меньше шагов
нужно, чтоб найти три простых числа рядом с 1000, чем рядом 100 000.

Смотрим на вермя: для 1 000 000 понадобилось приблизительно в 10 раз больше времени,
чем для 10 000, для 100 000 понадобилось приблизительно в 10 раз больше времени, чем
для 1000.

Ответ: да, кол-во времени пропорционально кол-ву затрачиваемых шагов.

~Упражнение 1.23~
Процедура smallest-divisor в начале этого раздела проводит множество лишних проверок:
после того, как она проверяет, делится ли число на 2, нет никакого смысла проверять
делимость на другие четные числа. Таким образом, вместо последовательности
2, 3, 4, 5, 6 . . . , используемой для test-divisor, было бы лучше использовать
2, 3, 5, 7, 9 . . . .

Чтобы реализовать такое улучшение, напишите процедуру next,
которая имеет результатом 3, если получает 2 как аргумент, а иначе возвращает свой
аргумент плюс 2.
Используйте (next test-divisor) вместо (+ test-divisor 1) в
smallest-divisor.

Используя процедуру timed-prime-test с модифицированной версией smallest-divisor,
запустите тест для каждого из 12 простых чисел, найденных в упражнении 1.22.
Поскольку эта модификация снижает количество шагов проверки вдвое, Вы должны ожидать
двукратного ускорения проверки. Подтверждаются ли эти ожидания?
Если нет, то каково наблюдаемое соотношение скоростей двух алгоритмов, и как Вы
объясните то, что оно отличается от 2?

#+BEGIN_SRC scheme
  (define (square x) (* x x))

  (define (divides? a b)
    (= (remainder b a) 0))

  (define (next test-divisor)
    (if (= test-divisor 2)
        3
        (+ test-divisor 2)))

  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (next test-divisor)))))

  (define (smallest-divisor n)
    (find-divisor n 2))

  (define (prime? n)
    (= n (smallest-divisor n)))

#+END_SRC

Судя по форматному выводу, для первой тройки чисел отклонение составляет 2-3
милисекунды, со второй тройкой чисел тоже почти не изменилась, как и с третьей.
Больше всего изменения коснулись последней тройки:

было:  1000003 *** 546     стало:  1000003 *** 389
       1000033 *** 546             1000033 *** 389
       1000037 *** 679             1000037 *** 342

В принципе, мы можем сказать, что получили двухкратный прирост производительности, т.к.
я думаю, что остальные результаты мало изменились по причине хорошой оптимизации кода
внутри интерпритатора и при неоптимальной версии smallest-divisor. На более больших
числах внутренняя оптимизация работала хуже.

P.S. Проверено на более больших числах. Гипотеза не подтвердилась, процедура с
первоначальной  версией smallest-divisor работает даже быстрее, чем с
оптимальной. Возможно, это все шутки интерпритатора, т.к. процедуры сравнительно
небольшие.

~Упражнение 1.24~
Модифицируйте процедуру timed-prime-test из упражнения 1.22 так, чтобы она использовала
fast-prime? (метод Ферма) и проверьте каждое из 12 простых чисел, найденных в этом
упражнении.
Исходя из того, что у теста Ферма порядок роста Θ(log n), то какого соотношения
времени Вы бы ожидали между проверкой на простоту поблизости от 1 000 000 и
поблизости от 1000?
Подтверждают ли это Ваши данные? Можете ли Вы объяснить наблюдаемое несоответствие,
если оно есть?

#+BEGIN_SRC scheme
  (define (report-prime start-time end-time)
    (display " *** ")
    (display (- (cdr end-time) (cdr start-time)))
    (display "\n")
    #t)

  (define (start-prime-test n start-time)
    (if (fast-prime? n 5)
        (report-prime start-time (gettimeofday))
        #f))

  (define (timed-prime-test n)
    (newline)
    (display n)
    (start-prime-test n (gettimeofday)))

#+END_SRC

Итак, если алгоритм растет как Θ(log n), то он растет медленнее, чем Θ(√n), т.к.
если n = 9, то логарифм от по основанию 3 равен 2 от 9. А вот квадратный корень из 9
= 3. 2 < 3, поэтому я думаю, что Θ(log n) растет медленнее.

Исходя из этого предположения можно сказать, что timed-prime-test, использующий метод
Ферма, должен работать быстрее, чем прежняя версия.

предыдущий результат:
1000003 *** 389
1000033 *** 389
1000037 *** 342

новый результат, если ставить проверку 5 раз:
1000003 *** 163
1000033 *** 285
1000037 *** 198


Мы видим, что новая версия работает в полтора-два раза быстрее. Схожесть на более
маленьких числах я объясняю оптимизацией интерпритатора.

~Вопросы:~
Как рассчитать время при проверке чисел для 1000 и для 1 000 000, не загружая в
интерпритатор? Понятно, что для 1000 будет меньше, но как рассчитать точно?

Метод Ферма вероятностный. Т.е. он должен отработать несколько раз, чтоб мы могли
считать его результат достаточно достоверным, в то время как prime? отрабатывает только
1 раз. Я могу запустить метод Ферма 10 000 раз, получить результат как от prime?, но
только метод Ферма в будет работать сильно дольше, хотя логарифмический рост медленнее
чем O(квадратный корень от n). И как быть тогда?


~Упражнение 1.25~
Лиза П. Хакер жалуется, что при написании expmod мы делаем много лишней работы. В конце
концов, говорит она, раз мы уже знаем, как вычислять степени, можно просто написать.

#+BEGIN_SRC scheme
  (define (expmod base exp m)
    (remainder (fast-expt base exp) m))
#+END_SRC

Права ли она? Стала бы эта процедура столь же хорошо работать при проверке простых
чисел?
Объясните.

Я думаю, что права, поскольку fast-expt работает по тому же механизму, что оригинальная
expod. Я думаю, что у обоих алгоритмов рост O(log n).

~Упражнение 1.26~

У Хьюго Дума большие трудности в упражнении 1.24. Процедура fast-prime? у него работает
медленнее, чем prime?. Хьюго просит помощи у своей знакомой Евы Лу Атор. Вместе изучая
код Хьюго, они обнаруживают, что тот переписал процедуру expmod с явным использованием
умножения вместо того, чтобы вызывать square:


#+BEGIN_SRC scheme
  (define (expmod base exp m)
    (cond ((= exp 0) 1)
          ((even? exp)
           (remainder (* (expmod base (/ exp 2) m)
                         (expmod base (/ exp 2) m))
                      m))
          (else
           (remainder (* base (expmod base (- exp 1) m))
                      m))))
#+END_SRC


Хьюго говорит: «Я не вижу здесь никакой разницы». «Зато я вижу, — отвечает Ева. —
Переписав процедуру таким образом, ты превратил процесс порядка Θ(log n) в процесс порядка
Θ(n)».
Объясните.

Процедура ~square~
#+BEGIN_SRC scheme
  (define (square x) (* x x))
#+END_SRC

Ответ: Хьюго исполняет одни и те же вычисления дважды, а затем умножает результат
вычислений друг на друга. Да, формально это дает тот же ответ, что при использовании
square, только вот в оригинальной процедуре вычисление проводится один раз и по мере
отката рекурсии назад мы возводим каждое промежуточное значение в квадрат, включая
результат от самого первого рекурсивного вызова. Это позволяет в два раза скорее
производить вычисление.

~Упражнение 1.27~
Покажите, что числа Кармайкла, перечисленные в сноске 47, действительно «обманывают»
тест Ферма: напишите процедуру, которая берет целое число n и проверяет, правда ли a^n
равняется a по модулю n для всех a < n, и проверьте эту процедуру
на этих числах Кармайкла.

Числа Кормайкла 561, 1105, 1729, 2465, 2821 и 6601.

Я взяла процедуры из теста Ферма и слегка их изменила.
#+BEGIN_SRC scheme
  (define (square x) (* x x))

  (define (expmod base exp m)
    (cond ((= exp 0) 1)
          ((even? exp)
           (remainder (square (expmod base (/ exp 2) m))
                      m))
          (else
           (remainder (* base (expmod base (- exp 1) m))
                      m))))

  (define (cormaickle-test n a)
    (cond ((= a n) #t)
          ((= (expmod a n n) a) (cormaickle-test n (+ 1 a)))
          (else #f)))
#+END_SRC

~Упражнение 1.28~
Один из вариантов теста Ферма, который невозможно обмануть, называется тест
Миллера–Рабина (Miller-Rabin test) (Miller 1976; Rabin 1980).
Он основан на альтернативной формулировке Малой теоремы Ферма, которая состоит в том,
что если n — простое число, а "a" — произвольное положительное целое число,
меньшее n, то a в n − 1-ой степени равняется 1 по модулю n.

Проверяя простоту числа  n методом Миллера–Рабина, мы берем случайное число a < n
и возводим его в (n − 1)-ю степень по модулю n с помощью процедуры expmod.
Однако когда в процедуре expmod мы проводим возведение в квадрат, мы проверяем,
не нашли ли мы «нетривиальный квадратный корень из 1 по модулю n»,
то есть число, не равное 1  или n − 1, квадрат которого по модулю n равен 1.
Можно доказать, что если такой нетривиальный квадратный корень из 1 существует,
то n не простое число. Можно, кроме того, доказать, что если n — нечетное
число, не являющееся простым, то по крайней мере для половины чисел a < n
вычисление a n−1 с помощью такой процедуры обнаружит нетривиальный квадратный корень
из 1 по модулю n (вот почему тест Миллера–Рабина невозможно обмануть).

Модифицируйте процедуру expmod так, чтобы она сигнализировала обнаружение
нетривиального квадратного корня из 1, и используйте ее для реализации теста
Миллера–Рабина с помощью процедуры, аналогичной fermat-test.
Проверьте свою процедуру на нескольких известных Вам простых и составных числах.
Подсказка: удобный способ заставить expmod подавать особый сигнал — заставить
ее возвращать 0.

Альтернативная формулировка малой теоремы Ферма:
a^(n - 1) = 1 (mod n)

Первая проверка:
«нетривиальный квадратный корень из 1 по модулю n» = чило в диапазоне от 2 до n - 2,
чей квадрат = 1 ( mod m), т.е. надо возвести число в квадрат, разделить на n, разделить
1 на n и сравнить остатки этих чисел. Если остатки равны, то исходное число не
простое.

Вторая проверка: если число нечетное и не простое, то минимум для половины чисел
a < n первая проверка даст положительный результат.

#+BEGIN_SRC scheme
  (define (square x) (* x x))

  (define (check n m)
    (if (and (not (= n 1))
             (not (= n (- m 1)))
             (= (remainder (square n) m)  1))
        0
        (remainder (square n) m)))

  (define (expmod base exp m)
    (cond ((= exp 0) 1)
          ((even? exp)
           (check (expmod base (/ exp 2) m) m))
          (else
           (remainder (* base (expmod base (- exp 1) m))
                      m))))

  (define (try-it a n)
    (= (expmod a (- n 1) n) 1))

  (define (m-r-test-iter n a positiv)
    (if (= a (- n 1))
        (> positiv (/ n 2))
        (if (try-it a n)
            (m-r-test-iter n (+ a 1) (+ 1 positiv))
            (m-r-test-iter n (+ a 1) positiv))))

  (define (m-r-test n)
    (m-r-test-iter n 1 0))
#+END_SRC


~Упражнение 1.29~
Правило Симпсона — более точный метод численного интегрирования, чем представленный
выше.

Представленный выше вариант:
#+BEGIN_SRC scheme
  (define (integral f a b dx)
    (define (add-dx x) (+ x dx))
    (* (sum f (+ a (/ dx 2)) add-dx b)
       dx))
#+END_SRC

С помощью правила Симпсона интеграл функции f между a и b приближенно вычисляется в
виде:

h[y0 + 4y1 + 2y2 + 4y3 + 2y4 + . . . + 2y n−2 + 4yn−1 + yn ]
3

где h = (b − a)/n, для какого-то четного целого числа n, а yk = f(a + kh).
(Увеличение n повышает точность приближенного вычисления.)
Определите процедуру, которая принимает в качестве аргументов f, a, b и n,
и возвращает значение интеграла, вычисленное по правилу Симпсона.
С помощью этой процедуры проинтегрируйте cube между 0 и 1 (с n = 100 и n = 1000) и
сравните результаты с процедурой integral, приведенной выше.

- n > 0
- h = (b − a)/n - это один шаг
- yk = f(a + kh); параметр функции f - это a + kh; k - коэфициент от 0 до n
  (предположительно)
находи Y через функцию, затем умножаем на k. Если коэфициент четный, все это умножается
на 2, если нечетный, то на 4, за исключением случая, когда k = 0 или k=n, тогда ничего
не умножаем
- a = нижний порог интегрирования (что бы это не значило)
- b = верхний порог интегрирования
- f - какая-то функция (в нашем случае будет cube)

#+BEGIN_SRC scheme
  (define (even? n)
    (= (remainder n 2) 0))

  (define (inc n)
    (+ 1 n))

  (define (simpson f a b n)
    (define (h)
      (/ (- b a) n))
    (define (funk k)
      (define (multiplier)
        (cond ((or (= k 0) (= k n)) 1)
              ((even? k) 2)
              (else 4)))
      (* (multiplier) (f (+ a (* k (h))))))
    (* (/ (h) 3)
       (sum funk 0 inc n)))

#+END_SRC

~Упражнение 1.30~
Процедура sum порождает линейную рекурсию. Ее можно переписать так, чтобы суммирование
выполнялось итеративно.

Оригинал:
#+BEGIN_SRC scheme

(define (sum term a next b)
    (if (> a b)
        0
        (+ (term a)
           (sum term (next a) next b))))

#+END_SRC

Мой вариант:
#+BEGIN_SRC scheme
  (define (my-sum term a next b)
    (define (iter a result)
      (if (> a b)
          result
          (iter (next a) (+ result (term a)))))
    (iter a 0))
#+END_SRC

~Упражнение 1.31~
Процедура sum — всего лишь простейшая из обширного множества подобных абстракций,
которые можно выразить через процедуры высших порядков. Напишите аналогичную
процедуру под названием product, которая вычисляет произведение значений функции
в точках на указанном интервале.
Покажите, как с помощью этой процедуры определить factorial.
Кроме того, при помощи product вычислите приближенное значение пи по формуле (см
стр. 73)

Реализовать в двух вариантах: хвостовая и нехвостовая рекурсия.

Формула факториала:
n! = n · (n − 1) · (n − 2) · · · 3 · 2 · 1

Процедура факториала:
#+BEGIN_SRC scheme

  (define (factorial n)
    (if (= n 1)
        1
        (* n (factorial (- n 1)))))

#+END_SRC

#+BEGIN_SRC scheme
  ;; нехвостовая рекурсия
  (define (product f a b next)
    (if (> a b )
        1
        (* (f a)
           (product f (next a) b next))))

  ;; хвостовая рекурсия
  (define (product f a b next)
    (define iter (a result)
      (if (> a b )
          result
          (iter (next a) (* result (term a))))))

  ;; определение факториала
  (define (my-factorial n)
    (define (inc n)
      (+ 1 n ))
    (define (identity x)
      x)
    (product identity 1 n inc))

  ; нахождение pi по формуле Уоллиса
  (define (pi n)
    (define (step x)
      (/ (* x x) (* (- x 1) (+ x 1))))
    (define (pi-next x)
      (+ x 2))
    (* 2.0 (product step 2 n pi-next)))
#+END_SRC


~Упражнение 1.32~
Покажите, что sum и product (упражнение 1.31) являются частными случаями еще более
общего понятия, называемого накопление (accumulation), которое комбинирует множество
термов с помощью некоторой общей функции накопления
(accumulate combiner null-value term a next b)
Accumulate принимает в качестве аргументов те же описания термов и диапазона,
что и sum с product, а еще процедуру combiner (двух аргументов),
которая указывает, как нужно присоединить текущий терм к результату накопления
предыдущих, и null-value, базовое значение, которое нужно использовать, когда термы
закончатся. Напишите accumulate и покажите, как и sum, и product можно определить в
виде простых вызовов accumulate.

Написать как хвостовую и нехвостовую рекурсию.

#+BEGIN_SRC scheme
  ;; хвостовая рекурсия
  (define (accumulate combiner null-value term a next b)
    (define (iter a accum)
      (if (> a b)
          accum
          (iter (next a) (combiner (term a) accum))))
    (iter a null-value))

  ;; нехвостовая рекурсия
  (define (accumulate combiner null-value term a next b)
    (if (> a b )
        null-value
        (combiner (term a)
                   (accumulate combiner null-value
                               term (next a) next b))))

  (define (new-product term a b next)
    (accumulate * 1 term a next b))

  (define (new-sum term a b next)
    (accumulate + 0 term a next b))

  ;; вспомогательные функции, чтоб "поиграться"
  (define (identity x)
    x)

  (define (inc n)
    (+ n 1))

  (define (square x)
    (* x x))
#+END_SRC

~Упражнение 1.33~

Можно получить еще более общую версию accumulate, если ввести понятие
фильтра (filter) на комбинируемые термы. То есть комбинировать только те термы,
порожденные из значений диапазона, которые удовлетворяют указанному условию.
Получающаяся абстракция filtered-accumulate получает те же аргументы, что и accumulate,
плюс дополнительный одноаргументный предикат, который определяет фильтр.
Запишите filtered-accumulate в виде процедуры.
Покажите, как с помощью filtered-accumulate выразить следующее:
а. сумму квадратов простых чисел в интервале от a до b (в предположении, что процедура
prime? уже написана);
б. произведение всех положительных целых чисел меньше n, которые просты по отношению к
n (то есть всех таких положительных целых чисел i < n, что НОД(i, n) = 1).

#+BEGIN_SRC scheme
  (define (filtered-accumulate combiner null-value term a next b filter)
    (define (iter a accum)
      (cond (( > a b) accum)
            ((filter a)
             (iter (next a) (combiner (term a) accum)))
            (else (iter (next a) accum))))
    (iter a null-value 0))

  ;; вспомогательные процедуры для подпунктов а и б
  (define (divides? a b)
    (= (remainder b a) 0))

  (define (find-divisor n test-divisor)
    (cond ((> (square test-divisor) n) n)
          ((divides? test-divisor n) test-divisor)
          (else (find-divisor n (+ test-divisor 1)))))

  (define (smallest-divisor n)
    (find-divisor n 2))

  (define (prime? n)
    (= n (smallest-divisor n)))

  ;; решение для a
  (define (sum-squares-primes a b )
    (define (inc x)
      (+ 1 x))
    (define (square x) (* x x))
    (filtered-accumulate + 0 square a inc b prime?))

  ;; решение для б
  (define (product-primes-for-n n)
    (define (gcd a b)
      (if (= b 0)
          a
          (gcd b (remainder a b))))
    (define (identity x)
      x)
    (define (inc x)
      (+ 1 x))
    (define (prime-for-n? g)
      (= (gcd g n) 1))
    (filtered-accumulate * 1 identity 1 inc n prime-for-n?))
#+END_SRC

~Упражнение 1.34~
Допустим, мы определили процедуру
#+BEGIN_SRC scheme
  (define (f g)
    (g 2))

  ;; тогда:
  (f square)
  => 4

  (f (lambda (z) (* z (+ z 1))))
  => 6
#+END_SRC

Что случится, если мы (извращенно) попросим интерпретатор вычислить комбинацию (f f)?
Объясните.

Ответ: мой интерпритатор выдал ошибку, думаю, дело в том, что функция должна принимать
1 аргумент. Первый вызов получает в качестве аргумента f функцию f. Функция f
подставляется вместо g, получает в качестве аргумента 2. Мы опускаемся на уровень
вложенности ниже, снова подставляем вместо g переданный параметр. В нашем случае
интерпритатор ожидает, что g - это одноаргументная процедура или предикат, но вместо
этого получает число. Отсюда ошибка.


~Упражнение 1.35~
Покажите, что золотое сечение φ (раздел 1.2.2) есть неподвижная точка трансформации
x→  1 + 1/x, и используйте этот факт для вычисления фи с помощью процедуры fixed-point.

φ^2 = φ + 1 - это формула золотого сечения

#+BEGIN_SRC scheme
  (define tolerance 0.00001)

  (define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2)) tolerance))
    (define (try guess)
      (let ((next (f guess)))
        (if (close-enough? guess next)
            next
            (try next))))
    (try first-guess))

  (fixed-point (lambda (x)
                 (+ 1 (/ 1 x)))
               1.0)

#+END_SRC

~Упражнение 1.36~
Измените процедуру fixed-point так, чтобы она печатала последовательность приближений,
которые порождает, с помощью примитивов newline и display, показанных в упражнении
1.22.

Затем найдите решение уравнения x^x = 1000 путем поиска неподвижной точки
x → log(1000)/ log(x). (Используйте встроенную процедуру Scheme log, которая вычисляет
натуральные логарифмы.) Посчитайте, сколько шагов это занимает при использовании
торможения усреднением и без него. (Учтите, что нельзя начинать fixed-point со значения 1,
поскольку это вызовет деление на log(1) = 0.)

Воспользовалась форматом, поскольку он удобнее.
#+BEGIN_SRC scheme
  (define tolerance 0.00001)

  (define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2)) tolerance))
    (define (try guess)
      (let ((next (f guess)))
        (format #t "next ~A\n" next)
        (if (close-enough? guess next)
            next
            (try next))))
    (try first-guess))

  (define (average x y)
    (/ (+ x y) 2))

  ;; с торможением (работает быстрее)
  (fixed-point (lambda (x)
                 (average x (/ (log 1000) (log x))))
               2.0)

  ;; без
  (fixed-point (lambda (x)
                 (/ (log 1000) (log x)))
               2.0)
#+END_SRC

~Упражнение 1.37~
Бесконечная цепная дробь имеет вид: (см стр. 82)

В качестве примера можно показать, что расширение бесконечной цепной дроби при всех Ni
и Di , равных 1, дает 1/φ, где φ — золотое сечение (описанное в разделе 1.2.2). Один из
способов вычислить цепную дробь состоит в том, чтобы после заданного количества
термов оборвать вычисление. Такой обрыв — так называемая конечная цепная дробь.

Предположим, что n и d — процедуры одного аргумента (номера элемента i),
возвращающие Ni и Di элементов цепной дроби. Определите процедуру cont-frac так,
чтобы вычисление (cont-frac n d k) давало значение k-элементной конечной цепной дроби.
Проверьте свою процедуру, вычисляя приближения к 1/φ с помощью

#+BEGIN_SRC scheme

  (cont-frac (lambda (i) 1.0)
             (lambda (i) 1.0)
             k)
#+END_SRC

Если Ваша процедура cont-frac порождает рекурсивный процесс, напишите вариант, кото-
рый порождает итеративный процесс. Если она порождает итеративный процесс, напишите
вариант, порождающий рекурсивный процесс.

Перевод:
- цепная дробь - это дробь, у которой в знаменателе стоит другая дробь, а у того
тоже стоит дробь и т.д. И так либо пока не встретим конец, тогда это будет конечная
цепная дробь, либо мы конца не будет, и тогда дробь бесконечная.
- если Ni = 1 или Di = 1, то мы имеем 1/φ, где φ — золотое сечение (почему?)
- n и d - это процедуры, принимающие 1 аргумент. Этот аргумент - коэфициент,т.е. i
Процедуры должны вернуть значение N и D с этим коэфициентом.
- процедура cont-frac принимает 2 функции и 1 аргумент, который будет аргументом
для этих функций

#+BEGIN_SRC scheme
  ;; нехвостовая рекурсия
  (define (cont-frac n d k)
    (define (rec i)
      (/ (n i) (+ (d i)
                  (if (> i k )
                      1
                      (rec (+ 1 i))))))
    (rec 1))

  ;; хвостовая
  (define (cont-frac n d k)
    (define (iter i accum)
      (if (> i k)
          accum
          (iter (+ 1 i) (/ (n i) (+ (d i) accum)))))
    (iter 1 1))

  ;; достаточно k = 13, чтоб получить 4 правильных знака после запятой
  (define (g-r k)
    (cont-frac (lambda (i) 1.0)
               (lambda (i) 1.0)
               k))



#+END_SRC

~Упражнение 1.38~
В 1737 году швейцарский математик Леонард Эйлер опубликовал статью De functionibus
Continuis, которая содержала расширение цепной дроби для e − 2, где e — основание
натуральных логарифмов. В этой дроби все N i равны 1, а D i последовательно
равны 1, 2, 1, 1, 4, 1, 1, 6, 1, 1, 8, . . .
Напишите программу, использующую Вашу процедуру cont-frac из упражнения 1.37 для
вычисления e на основании формулы Эйлера.


#+BEGIN_SRC scheme
  ;; вариант по найденной в интернете формуле
  (define (euler-e k)
    (let ((e (cont-frac (lambda (i) 1.0)
                        (lambda (i) (- (* i 4) 2))
                        k)))
      (+ 2 e)))

  ;; подсмотренное
  (define (euler-e k)
    (+ 2 (cont-frac (lambda (i) 1.0)
               (lambda (i)
                 (if (= (remainder i 3) 2)
                     (* 2 (/ (+ i 1) 3))
                     1))
               k)))

  #+END_SRC

~Упражнение 1.39~
Представление тангенса в виде цепной дроби было опубликовано в 1770 году немецким
математиком Й.Х. Ламбертом (см. стр 82), где x дан в радианах. Определите процедуру
(tan-cf x k), которая вычисляет приближение к тангенсу на основе формулы Ламберта.
K указывает количество термов, которые требуется вычислить, как в упражнении 1.37.

#+BEGIN_SRC scheme
  (define (tan-cf x k)
    (define (iter x y i k)
      (- y
         (if (> i k)
             0
             (iter x (+ y 2) (+ i 1) k))))
    (/ x (iter (* x x) 1 1 k)))
#+END_SRC

~Упражнение 1.40~
Определите процедуру cubic, которую можно было бы использовать совместно с процедурой
newtons-method в выражениях вида (newtons-method (cubic a b c) 1)
для приближенного вычисления нулей кубических уравнений x^3 + ax^2 + bx + c.

#+BEGIN_SRC scheme
  (define dx 0.00001)

  (define tolerance 0.00001)

  (define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2)) tolerance))
    (define (try guess)
      (let ((next (f guess)))
        (if (close-enough? guess next)
            next
            (try next))))
    (try first-guess))

  (define (deriv g)
    (lambda (x)
      (/ (- (g (+ x dx)) (g x))
         dx)))

  (define (newton-transform g)
    (lambda (x)
      (- x (/ (g x) ((deriv g) x)))))

  (define (newtons-method g guess)
    (fixed-point (newton-transform g) guess))

  (define (cube x)
    (* x x x))
  (define (square x)
    (* x x))

  (define (cubic a b c)
    (lambda (x)
      (+ (cube x) (* a (square x)) (* b x) c)))

  (newtons-method (cubic 0 0 -8) 1)
#+END_SRC

~Упражнение 1.41~
Определите процедуру double, которая принимает как аргумент процедуру с одним
аргументом и возвращает процедуру, которая применяет исходную процедуру дважды.
Например, если процедура inc добавляет к своему аргументу 1, то (double inc)
должна быть процедурой, которая добавляет 2. Скажите, какое значение возвращает
(((double (double double)) inc) 5)

#+BEGIN_SRC scheme
  (define (double g)
    (lambda (x)
      (g (g x))))

  (define (inc x)
    (+ x 1))

  ((double inc) 1)
#+END_SRC

(((double (double double)) inc) 5) => 21

Чтобы 5 превратилась в 21, нужно, чтоб inc отработал 16 раз (21 - 5 = 16)
Соответственно, нужно, чтоб double сработал 8 раз, что мы и имеем.
Поскольку мой интерпритатор использует нормальный порядок, то сначала
мы подставим все полученные лямбды от в места вызова double (лямбды
окажутся вложенными друг в друга), а затем передадим туда процедуру inc и
аргумент 5, который будет увеличиваться при подъеме от самого низкого уровня
вложенности до самого высокого.

~Упражнение 1.42~
Пусть f и g — две одноаргументные функции. По определению, композиция (composition) f и
g есть функция x → f (g(x)).
Определите процедуру compose которая реализует
композицию.
Например, если inc — процедура, добавляющая к своему аргументу 1,
((compose square inc) 6) => 49

#+BEGIN_SRC scheme
  (define (compose f g)
    (lambda (x)
      (f (g x))))

  (define (inc x)
    (+ x 1))

  (define (square x)
    (* x x))
#+END_SRC

~Упражнение 1.43~
Если f есть численная функция, а n — положительное целое число, то мы можем построить
n-кратное применение f , которое определяется как функция, значение которой в точке x
равно f (f (. . . (f (x)) . . .)).
Например, если f есть функция x → x + 1, то n-кратным применением f
будет функция x → x + n. Если f есть операция возведения в квадрат, то n-кратное
применение f есть функция, которая возводит свой аргумент в 2n-ю степень.
Напишите процедуру, которая принимает в качестве ввода процедуру, вычисляющую f ,
и положительное целое n, и возвращает процедуру, вычисляющую n-кратное применение f .
Требуется, чтобы Вашу процедуру можно было использовать в таких контекстах:
((repeated square 2) 5) => 625
Подсказка: может оказаться удобно использовать compose из упражнения 1.42.

Иными словами, процедра должна принимать функцию и кол-во раз, сколько эту функцию
надо применить к аргументу. А возвращать должна процеудуру, которая применяет
фнкцию к аргументу заданное кол-во раз.
#+BEGIN_SRC scheme
  (define (inc x)
    (+ x 1))

  (define (square x)
    (* x x))

  (define (repeated f n)
    (lambda (x)
      (define (test x n)
        (if (= n 0)
            x
            (test (f x) (- n 1))))
      (test x n)))

  ((repeated square 2) 5) => 625
  ((repeated inc 19) 5) => 24

#+END_SRC

~Упражнение 1.44~
Идея сглаживания (smoothing a function) играет важную роль в обработке сигналов. Если f
— функция, а dx — некоторое малое число, то сглаженная версия f есть функция, значение
которой в точке x есть среднее между f (x − dx), f (x) и f (x + dx).
Напишите процедуру smooth, которая в качестве ввода принимает процедуру,
вычисляющую f , и возвращает процедуру, вычисляющую сглаженную версию f . Иногда бывает
удобно проводить повторное сглаживание (то есть сглаживать сглаженную функцию и т.д.),
получая n-кратно сглаженную функцию (n-fold smoothed function).
Покажите, как породить n-кратно сглаженную функцию с помощью smooth и
repeated из упражнения 1.43.

#+BEGIN_SRC scheme
  (define (inc x)
    (+ x 1))

  (define (square x)
    (* x x))

  (define (smooth f)
    (define dx 0.01)
    (lambda (x)
      (/ (+ (f (- x dx)) (f x) (f (+ x dx))) 3)))

  (define (repeated f n)
    (lambda (x)
      (define (test x n)
        (if (= n 0)
            x
            (test (f x) (- n 1))))
      (test x n)))

  ((repeated (smooth square) 2) 5)
#+END_SRC

~Упражнение 1.45~.
В разделе 1.3.3 мы видели, что попытка вычисления квадратных корней путем наивного
поиска неподвижной точки y → x/y не сходится, и что это можно исправить путем торможения
усреднением. Тот же самый метод работает для нахождения кубического корня как
неподвижной точки y → x/y^2 , заторможенной усреднением.
К сожалению, этот процесс не работает для корней четвертой степени — однажды
примененного торможения усреднением недостаточно, чтобы заставить сходиться процесс
поиска неподвижной точки y → x/y^3 . С другой стороны, если мы применим торможение
усреднением дважды (т.е. применим торможение усреднением к результату торможения
усреднением от y → x/y^3 ), то поиск неподвижной точки начнет сходиться. Проделайте
эксперименты, чтобы понять, сколько торможений усреднением нужно, чтобы вычислить
корень n-ой степени как неподвижную точку на основе многократного торможения усреднением
функции y → x/y n−1 . Используя свои результаты для того, напишите простую процедуру
вычисления корней n-ой степени с помощью процедур fixed-point, average-damp и repeated
из упражнения 1.43. Считайте, что все арифметические операции, какие Вам понадобятся,
присутствуют в языке как примитивы.

#+BEGIN_SRC scheme
  (define (inc x)
    (+ x 1))

  (define (square x)
    (* x x))

  (define tolerance 0.00001)

  (define (fixed-point f first-guess)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2)) tolerance))
    (define (try guess)
      (let ((next (f guess)))
        (if (close-enough? guess next)
            next
            (try next))))
    (try first-guess))


  (define (average x y)
    (/ (+ x y) 2))

  ;; вычисляет среднее между иксом и результатом, который мернет функция с параметром
  ;; икс
  (define (average-damp f)
    (lambda (x) (average x (f x))))

  (define (repeated f n)
    (lambda (x)
      (define (test x n)
        (if (= n 0)
            x
            (test (f x) (- n 1))))
      (test x n)))

  ((repeated sqrt 2) 16)

  (define (even? n)
    (= (remainder n 2) 0))

  (define (fast-expt b n)
    (cond ((= n 0) 1)
          ((even? n) (square (fast-expt b (/ n 2))))
          (else (* b (fast-expt b (- n 1))))))

  (define (log2 x)
      (/ (log x) (log 2)))

  (define (nth-root-empirical n x)
    (define (f y) (/ x (fast-expt y (- n 1))))
    (define damp-count (floor (log2 n)))
    (fixed-point ((repeated average-damp damp-count) f) 1.0))
#+END_SRC

~Упражнение 1.46~
Некоторые из вычислительных методов, описанных в этой главе, являются примерами
чрезвычайно общей вычислительной стратегии, называемой пошаговое улучшение
(iterative improvement). Пошаговое улучшение состоит в следующем: чтобы что-то
вычислить, нужно взять какое-то  начальное значение, проверить, достаточно ли оно
хорошо, чтобы служить ответом, и если нет, то улучшить это значение и продолжить
процесс с новым значением. Напишите процедуру iterative-improve, которая принимает
в качестве аргументов две процедуры: проверку, достаточно ли хорошо значение,
и метод улучшения значения. Iterative-improve должна возвращать процедуру,
которая принимает начальное значение в качестве аргумента и улучшает его, пока оно не
станет достаточно хорошим.
Перепишите процедуру sqrt из раздела 1.1.7 и процедуру fixed-point из раздела 1.3.3 в
терминах iterative-improve.

#+BEGIN_SRC scheme
  (define (iterative-improve check method)
    (lambda (x)
      (define (try x)
        (let ((next (method x)))
          (format #t "x ~A next ~A\n" x next)
          (if (check x next)
              next
              (try next))))
      (try x)))

  (define (new-fixed-point f first-guess)
    (define tolerance 0.00001)
    (define (close-enough? v1 v2)
      (< (abs (- v1 v2)) tolerance))
    ((iterative-improve close-enough? f) first-guess))

  (define (new-sqrt x)
    (define tolerance 0.00001)
    (define (average x y)
      (/ (+ x y) 2))
    ((iterative-improve (lambda (guess next)
                          (format #t "guess ~A next ~A x ~A\n" guess next x)
                          (< (abs (- (square next) x))
                             tolerance))
                        (lambda (guess)
                          (average guess (/ x guess)))) 1.0))

#+END_SRC
